vich_uploader:
    db_driver: orm

    mappings: 
        chapterOne_image:
            uri_prefix: /images/chapterOne
            upload_destination: '%kernel.project_dir%/public/images/chapterOne'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
