vich_uploader:
    db_driver: orm

    mappings: 
        chapterOne_image:
            uri_prefix: '/public/images/chapterOne'
            upload_destination: '%kernel.project_dir%/public/images/chapterOne'
            namer: vich_uploader.namer_uniqid
           



