vich_uploader:
    db_driver: orm

    mappings: 
        chapterOne_image:
            uri_prefix: images/chapterOne_image/
            upload_destination: '%kernel.project_dir%/../public/images/chapterOne_image'
            namer: vich_uploader.namer_uniqid
           



