vich_uploader:
    db_driver: orm

    mappings: 
        chapterOne_image:
            uri_prefix: public/images/chapterOne
            upload_destination: '%kernel.project_dir%/public/images/chapterOne'
            inject_on_load: true 
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
