vich_uploader:
    db_driver: orm

    mappings: 
        chapterOne_image:
            uri_prefix: '/public/images/chapterOne'
            upload_destination: '././public/images/chapterOne'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
           



